hash-format = "sha256"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "ea430db88d8f190a053e4f3c662d2a59b6a7508778525034f2b20037ee074aec"
metafile = true

[[files]]
file = "mods/advancement-plaques.pw.toml"
hash = "f2a3d2af3f3ec8ed1bcdd436a76d89ec9655f20809c2274cb1be5392bb3e904e"
metafile = true

[[files]]
file = "mods/advancementinfo.pw.toml"
hash = "bb6c349471139b104a3d8001650ecaee747b596e1f5ca865157a8026e8182f61"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "7d44149b8b22e0b19b082f49809edfc1b5f170e5d1d297cd73ae88c0b432c3ab"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "e12dce3e543168379a2856c66064ee2001e6420a9dfc6163f37b78e518947456"
metafile = true

[[files]]
file = "mods/better-ping-display-fabric.pw.toml"
hash = "8f54b2270c2d87b56a73b4355305cc4a4dd277330cad97d137b98073ec0d8e83"
metafile = true

[[files]]
file = "mods/better-stats.pw.toml"
hash = "c4c11bc748458978b676b2a5cef87b5b8548c2289e9c199f225f941fb1593c9d"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "a1e024094c28068c99a6da1c5867cbd4e66a315718039659bfa533a138762d9e"
metafile = true

[[files]]
file = "mods/bookshelf-lib.pw.toml"
hash = "0b5feeae74fe992084ec5cb12eab3404ddd5054e85c9006f7ba4d65f209de13f"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "1173755b093b4f9a8aca00520d87bc35178fe19c54e59debe5c48d0c9063b91c"
metafile = true

[[files]]
file = "mods/cicada.pw.toml"
hash = "d226ea199a740bff4e07877a952dc6972273fb92fcddd258a8989bfbede63a8d"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "41a3dc271859b118417946d2fdb2408523563b2f4f49048073672a342fb1aebf"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "ca80c5f6b0faca95bbc06192a3da36446ff396b5e6e0304f6779269b60bbdd9d"
metafile = true

[[files]]
file = "mods/decorative-blocks.pw.toml"
hash = "1e4682a6a43156f149bdf2b0187b78fa2bd9ac201d4544c62942368e4954b038"
metafile = true

[[files]]
file = "mods/detail-armor-bar.pw.toml"
hash = "deeaa932ef85c1717f3c0894e99790f763ec478ff84ed3cc3d9b8d5836fcf687"
metafile = true

[[files]]
file = "mods/eating-animation.pw.toml"
hash = "5af1714d668d18cf7c500218ad61a9e904fbfce74884c5ae5364434a6c9dc43f"
metafile = true

[[files]]
file = "mods/enchantment-descriptions.pw.toml"
hash = "8ca413f9c2a155068d71e0057b23d8a199473fb78b37fe1ea864b5455e997a26"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "f1d9c0910c3172c83058cc6d9af49e9b8dd9a6e410b0113e41077a373a0646a0"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "58a487d9e3761d18f529cf141c873ea054e8f26c5e90601a3c8cf60fc723b22d"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "91f45174d8627de2d04922bcf83b4b7c31188fbfc748240fcca27ea4f3282e93"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "2b7949e506ba69c57139127c0ccc6caf5a9ec5ec97788b81288118db3d7c2ad3"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "d7c055f277c1751122d9abc5f09015e629699e04a9383cd0c666b33436293079"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "86cbfa8adbbb8be527f95aca49b427f892aa780773df141dfd7f4ffd02740bbd"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "4449401b59481016fa2a66d6e749795129160cb1ab3e7932e15033c6b5815455"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "21d2df923fa369d69a40d69f6466153146bf403367430eaeb2569c1554857df8"
metafile = true

[[files]]
file = "mods/iceberg.pw.toml"
hash = "f669b069214a8e88d17066ff6715fe131568cd190450ba408b4c2c5479a1a263"
metafile = true

[[files]]
file = "mods/invmove.pw.toml"
hash = "62a5e15ac115d87e69788ee67f58adc82bd09c8edb7e32d78ec421280d887fd3"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "99efc9e805ce2888680d3cacb9be65733c6d4a8cfcb77e1976205f758db24346"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "d5faaf6d7e4be8bdf9b1b200edee175c2704ce13abad9d1951a4d4a45b432d4e"
metafile = true

[[files]]
file = "mods/legendary-tooltips.pw.toml"
hash = "ef561650c251d4780b9cb948ddcacd4f43abe0dc0e31cb1aa22bac0147fe805e"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "a08a445002542d96a8481654c3f4b5e2d3c064f77b477aeaa3a1d1c3cd396ca8"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "ede2f61d6b592f44294fa8790c2f050729c487aa86aba09034f2ef30d45e0e93"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "d7145fd1bd8b4bb6a3b84652a96a68870fb3ab32230f27520bb9362fd17ec39f"
metafile = true

[[files]]
file = "mods/morechathistory.pw.toml"
hash = "3dc86c0b4d31199f6f8579b8460686201ce8b9c87e1be5afaf50be9995add1e0"
metafile = true

[[files]]
file = "mods/naturalist.pw.toml"
hash = "4a47f9115e5b8a3a68aceef941d146374e5b76958347ee81aede776c2100185f"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "89ed99a0798a5e1300434359762c968536593279493f68b321a565fb1343f75c"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
hash = "b63b338a1edc89356687477a15e6d230713cf875f9552f1616406f0ef3f273c7"
metafile = true

[[files]]
file = "mods/plagues-chat-timestamps.pw.toml"
hash = "123fc94f80e7d3a6ad0d962ec0549b3200cd554c26667f3233f2f30f7221d552"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
hash = "a9769ced0531122518321833966d375196753db1c3a47b975aed4bb6837fae7a"
metafile = true

[[files]]
file = "mods/prism-lib.pw.toml"
hash = "0ba23afebc8a761538a860cf9b21d6f456cfecf4573249dae9c6d7b1f3d43089"
metafile = true

[[files]]
file = "mods/raised.pw.toml"
hash = "d4f3d1a419f17ab8672b5d5388a0e1bcf0ced6f386777556e061461db85958c8"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "4a7d1e46795d2d83b18db85d8dbc63740a1d337e12d2b9e550378de59f2b23ab"
metafile = true

[[files]]
file = "mods/rei.pw.toml"
hash = "657ff0025d408f1021309ce5c759821d1f48e397811cc0da6f0b0400827896fa"
metafile = true

[[files]]
file = "mods/show-me-your-skin.pw.toml"
hash = "f29ba19cab72bdca9cbf01a557f5fb78513412094d4d4051295ab34ff1a86d9d"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "8ad07191dfdea31249b4416a390c1cdf1d4ff1938cf9f8a617f98f7a08c5356c"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "ecf8e1df2361e5f1d090f83eee16c449ff1021dfb2da46474a72726406d5d535"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "5cd3420078c7c24bf7414c7243a69b2d2a21c3c5e29150444697b11a001c44d8"
metafile = true

[[files]]
file = "mods/tcdcommons.pw.toml"
hash = "47634b4eedae148767c2dc94236c8f07054a533139400404d74deaf088348a08"
metafile = true

[[files]]
file = "mods/visuality.pw.toml"
hash = "407b6a954f9c3aee145dfa649eaa0b336a6b31d7660476c81cba1da1f6ff54e3"
metafile = true

[[files]]
file = "mods/wakes.pw.toml"
hash = "24cfa457173f8fd0aec773a4437c86dc22a9ef41c73514a2237160b514ff837d"
metafile = true

[[files]]
file = "mods/wavey-capes.pw.toml"
hash = "5fa91b45e2fdca864ceb74134974d9a668081b052adde4742db35494e691777e"
metafile = true

[[files]]
file = "mods/wildlife-fabric.pw.toml"
hash = "6110a721acb5ed26ac1514767c6150b42801cf5d507deaf0ce055daece2cbb95"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "8305bf17272f0c579b0930b751c12089de9fb157dbdb5c080836ce3daad310b5"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "d2d5a9c835661b4f6f718fd057f03594b87aa49d1bcd9711af8553e51ea4a6fb"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations.pw.toml"
hash = "bf6bf356ece200c132c604c1cdd981c8a7baf6a30ed05fa057fdfc0444df779d"
metafile = true
