name = "Bubus"
author = "Coutinho"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1717b6291db2cfb4ebbe4778c09cc6cb0b0cecb29487de628df1952a310ee51c"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
